import { Inter } from "next/font/google";
import "./globals.css";
import { TodoProvider } from "@/context/todoContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<TodoProvider>
					<main className=" min-h-screen max-w-5xl bg-red-400 mx-auto  p-24 flex  justify-center">
						{children}
					</main>
				</TodoProvider>
			</body>
		</html>
	);
}
